apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-router
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-router
  template:
    metadata:
      labels:
        app: backend-router
    spec:
      containers:
        - name: backend-router
          image: nginx:1.27-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: backend-router-config
