apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-router-config
  namespace: bookstore-ns
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location /books {
          proxy_pass http://book-service.bookstore-ns.svc.cluster.local:3000;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /customers {
          proxy_pass http://customer-service.bookstore-ns.svc.cluster.local:3000;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
